### ISSUE TITLE
PWA IOS compatibility

### ISSUE THREAD

**Issue by nikpakar** [holtwick/briefing#41] opened 2020-05-15 13:23 UTC
PWA looks perfectly fine on android, and also perfectly fine in IOS safari. But when added to home screen in IOS, media access seems unavailable.

Can this be IOS restriction at this moment ?

**Comment by holtwick** [comment] 2020-05-15 13:27
I cannot reproduce. Did you skip the authorization screen? Which iOS version?

![IMG_8A6CBD6116EB-1](https://user-images.githubusercontent.com/49557/82055281-8bb4f180-96c0-11ea-9d71-11deb5027841.jpeg)

**Comment by nikpakar** [comment] 2020-05-15 15:32
IOS 13.3.1, iPhone 6s. Never asked for permission.

**Comment by holtwick** [comment] 2020-05-15 15:42
iOS 13.4.1 seems to be the most recent one. Would be interesting to know if it works there for you or breaks as well. 

Currently there is no way to get to the error logs easily. Opened #42

**Comment by nikpakar** [comment] 2020-05-15 16:45
Upgraded to IOS 13.4.1. Works fine now.

**Comment by holtwick** [comment] 2020-05-15 16:47
Great, thanks. I consider this being an iOS bug then that has been fixed with the latest update. Thanks for testing!

**Closed by holtwick** 2020-05-15 16:47 UTC
Labels: bug

**Comment by nikpakar** [comment] 2020-05-15 17:48
You are welcom! great work and the PWA brings this to whole new native feel.

Would it be a good idea to always prompt for a PWA installation when visit from mobile browser ? I mean prompt for add to home screen from the app itself.

**Comment by holtwick** [comment] 2020-05-15 18:02
Android does it out of the box. Certainly this would be a nice idea for iOS as well.
